// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/thuc201995/xoso/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetByDateEndpoint     endpoint.Endpoint
	GetByProvinceEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.XosoService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GetByDateEndpoint:     MakeGetByDateEndpoint(s),
		GetByProvinceEndpoint: MakeGetByProvinceEndpoint(s),
	}
	for _, m := range mdw["GetByDate"] {
		eps.GetByDateEndpoint = m(eps.GetByDateEndpoint)
	}
	for _, m := range mdw["GetByProvince"] {
		eps.GetByProvinceEndpoint = m(eps.GetByProvinceEndpoint)
	}
	return eps
}
