// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/thuc201995/xoso/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetsEndpoint endpoint.Endpoint
	BarEndpoint  endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.XosoService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		BarEndpoint:  MakeBarEndpoint(s),
		GetsEndpoint: MakeGetsEndpoint(s),
	}
	for _, m := range mdw["Gets"] {
		eps.GetsEndpoint = m(eps.GetsEndpoint)
	}
	for _, m := range mdw["Bar"] {
		eps.BarEndpoint = m(eps.BarEndpoint)
	}
	return eps
}
