// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	http "github.com/go-kit/kit/transport/http"
	"github.com/gorilla/mux"
	endpoint "github.com/thuc201995/xoso/pkg/endpoint"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeGetByDateHandler(m, endpoints, options["GetByDate"])
	makeGetByProvinceHandler(m, endpoints, options["GetByProvince"])
	makeGetXSMTByDateHandler(m, endpoints, options["GetXSMTByDate"])
	makeGetMTByProvinceHandler(m, endpoints, options["GetMTByProvince"])
	return m
}
